#include "ite/itu.h"

extern void TouchCalibrationReset(void);
extern void ScreensaverReset(void);
extern void UpgradeReset(void);
extern void MainReset(void);
//extern void MainMenuReset(void);
extern void CalendarReset(void);
extern void ClockReset(void);
extern void CameraReset(void);
extern void CameraOutdoorReset(void);
extern void CameraViewReset(void);
extern void HouseReset(void);
extern void AirConditionerReset(void);
extern void VoiceMemoReset(void);
extern void PhoneReset(void);
extern void PhoneResidentReset(void);
extern void PhoneAdminReset(void);
extern void PhoneMiscReset(void);
extern void PhoneContactReset(void);
extern void PhoneContactKeyboardReset(void);
extern void CallingReset(void);
extern void CalledReset(void);
extern void MessageReset(void);
extern void MessageVideoReset(void);
extern void MessageVideoViewReset(void);
extern void MessageRecordReset(void);
extern void MessageRecordViewReset(void);
extern void MessageServiceReset(void);
extern void MessageServiceViewReset(void);
extern void GuardReset(void);
extern void GuardMainReset(void);
extern void GuardCheckReset(void);
extern void GuardUnguardReset(void);
extern void GuardLogReset(void);
extern void GuardStatusReset(void);
extern void GuardPasswordReset(void);
extern void GuardUserReset(void);
extern void GuardUserSettingDetailReset(void);
extern void SettingReset(void);
extern void SettingDisplayReset(void);
extern void SettingSoundReset(void);
extern void SettingVoiceReset(void);
extern void SettingVoiceKeyboardReset(void);
extern void SettingVoiceQRCodeReset(void);
extern void SettingVoiceDeleteUserReset(void);
extern void SettingDisturbReset(void);
extern void SettingLangReset(void);
extern void SettingNetworkReset(void);
extern void SettingWiFiSsidReset(void);
extern void SettingWiFiPasswordReset(void);
extern void SettingWiFiNetworkReset(void);
extern void SettingSensorReset(void);
extern void SettingTerminalReset(void);
extern void SettingDoorCameraReset(void);
extern void SettingMiscReset(void);
extern void SettingMiscWarnReset(void);
extern void SettingMiscDoorCameraReset(void);
extern void SettingSysInfoReset(void);
extern void AudioPlayerReset(void);
extern void VideoPlayerReset(void);
extern void VideoViewReset(void);
extern void ImagePlayerReset(void);
extern void ImageViewReset(void);
extern void VideoRecordReset(void);
extern void Called1Reset(void);

void resetScene(void)
{
	TouchCalibrationReset();
    ScreensaverReset();
    UpgradeReset();
    //MainReset();
    CalendarReset();
    ClockReset();
    CameraReset();
    CameraOutdoorReset();
    CameraViewReset();
    HouseReset();
    AirConditionerReset();
    VoiceMemoReset();
    PhoneReset();
    PhoneResidentReset();
    PhoneAdminReset();
    PhoneMiscReset();
    PhoneContactReset();
    PhoneContactKeyboardReset();
	CallingReset();    
	CalledReset();
	MessageReset();
	MessageVideoReset();
    MessageVideoViewReset();
	MessageRecordReset();
    MessageRecordViewReset();
	MessageServiceReset();
	MessageServiceViewReset();
    GuardReset();
    GuardMainReset();
    GuardCheckReset();
    GuardUnguardReset();
    GuardLogReset();
    GuardStatusReset();
    GuardPasswordReset();
    GuardUserReset();
    GuardUserSettingDetailReset();
    SettingReset();
    SettingDisplayReset();
    SettingSoundReset();
    SettingVoiceReset();
    SettingVoiceKeyboardReset();
    SettingVoiceQRCodeReset();
    SettingVoiceDeleteUserReset();
    SettingDisturbReset();
    SettingLangReset();
    SettingNetworkReset();
    SettingWiFiSsidReset();
    SettingWiFiPasswordReset();
    SettingWiFiNetworkReset();
    SettingSensorReset();
    SettingTerminalReset();
    SettingDoorCameraReset();
    SettingMiscReset();
    SettingMiscWarnReset();
    SettingMiscDoorCameraReset();
    SettingSysInfoReset();
    AudioPlayerReset();
    VideoPlayerReset();
    VideoViewReset();
    ImagePlayerReset();
    ImageViewReset();
    VideoRecordReset();
	Called1Reset();
}
